[workspace]
resolver = "3"
members = ["example"]

[workspace.package]
version = "0.1.0"
description = ""
documentation = ""
homepage = ""
repository = ""
authors = []
keywords = []
categories = []

edition = "2024"
rust-version = "1.94.1"

[workspace.lints.clippy]
needless_return = "allow"
new_without_default = "warn"
incompatible_msrv = "forbid"
allow_attributes_without_reason = "deny"
branches_sharing_code = "warn"

[profile.release]
lto = true
codegen-units = 1

[workspace.dependencies]
example = { path = "example" }
