[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
description = ""
documentation = ""
homepage = ""
repository = ""
authors = []
keywords = []
categories = []

edition = "2024"
rust-version = "1.85.1"

[workspace.lints.clippy]
perf = { level = "deny", priority = -1 }

allow_attributes_without_reason = "deny"
branches_sharing_code = "warn"
collapsible_else_if = "deny"
incompatible_msrv = "forbid"
needless_return = "allow"
new_without_default = "warn"
str_to_string = "warn"

[profile.release]
lto = true
codegen-units = 1

[workspace.dependencies]
example = { path = "crates/example" }
